app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::resource('herramienta', 'HerramientaController');

Route::get('graciaspago',function(){

	$datos = \App\Ordenes::find(1);
	//dd($datos->inventario->descr);
	//return view('correos/graciaspago', ['datos' => $datos]);
});

Route::resource('mail','MailController');
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

//Route::pattern('id', '\d+');  //Se define solo los parametros van a hacer numeros
Route::get('/', 'PrincipalController@index');

Route::get('usuarios/{id}/restaurar', [
	'uses' => 'UsersController@restaurar',
	'as' => 'usuarios.restaurar'
	]);
Route::get('usuarios/eliminada', 'UsersController@eliminada');
Route::resource('usuarios','UsersController');


Route::resource('movil','MovilController');

Route::resource('migracion', 'MigracionController');
Route::get('migracion/imagenes', [
	'uses' => 'MigracionController@imagenes',
	'as' => 'migracion.imagenes']);
Route::post('migracion/saveimagenes', [
	'uses' => 'MigracionController@saveimagenes',
	'as' => 'migracion.saveimagenes']);
/*
Route::controller('imagenes', 'ImagenesController', [
    'anyData'  => 'imagenes.data',
    'getIndex' => 'imagenes',]);
*/

Route::get('imagenes/data', [
	'uses' => 'ImagenesController@AnyData',
	'as' => 'imagenes.data']);

/*Route::get('imagenes/index', [
	'uses' => 'ImagenesController@index',
	'as' => 'imagenes.index']);
*/
Route::get('imagenes/galeria', [
	'uses' => 'ImagenesController@galeria',
	'as' => 'imagenes.galeria']);

Route::resource('imagenes', 'ImagenesController');


//Route::controller('formulario', 'FormularioController');
Route::resource('login', 'LoginController');
Route::get('/logout', 'LoginController@logout');

//Route::controller('configuracion', 'ConfiguracionController');

//Route::resource('login','LoginController');

Route::resource('configuracion','ConfiguracionController');
Route::get('configuracion/{id}/destroy', [
	'uses' => 'ConfiguracionController@destroy',
	'as' => 'configuracion.destroy'
	]);


Route::get('banco/{id}/restaurar', [
	'uses' => 'BancoController@restaurar',
	'as' => 'banco.restaurar'
	]);
Route::get('banco/eliminada', 'BancoController@eliminada');
Route::get('banco/listado', 'BancoController@listado');

Route::resource('banco','BancoController');
Route::get('banco/{id}/destroy', [
	'uses' => 'BancoController@destroy',
	'as' => 'banco.destroy'
	]);

Route::get('encomienda/eliminada', 'EncomiendaController@eliminada');
Route::resource('encomienda','EncomiendaController');
Route::get('encomienda/{encomienda}/destroy', [
	'uses' => 'EncomiendaController@destroy',
	'as' => 'encomienda.destroy'
	]);

/*
Route::get('encomienda/eliminada', [
	'uses' => 'EncomiendaController@eliminada',
	'as' => 'encomienda.eliminada'
	]);
*/
Route::get('encomienda/{id}/restaurar', [
	'uses' => 'EncomiendaController@restaurar',
	'as' => 'encomienda.restaurar'
	]);

Route::get('inventario/{id}/cambiaroferta/{page}', [
	'uses' => 'InventarioController@cambiaroferta',
	'as' => 'inventario.cambiaroferta'
	]);

Route::get('inventario/{id}/cambiarestatus/{page}', [
	'uses' => 'InventarioController@cambiarestatus',
	'as' => 'inventario.cambiarestatus'
	]);

Route::get('inventario/{id}/restaurar', [
	'uses' => 'InventarioController@restaurar',
	'as' => 'inventario.restaurar'
	]);
Route::get('inventario/eliminada', 'InventarioController@eliminada');
Route::resource('inventario','InventarioController');
Route::get('inventario/{id}/destroy', [
	'uses' => 'InventarioController@destroy',
	'as' => 'inventario.destroy'
	]);

/*
Route::post('ordene/updatenviar', function (Request $request)
	{
		return $request->all();
	});*/

Route::post('ordene/updatenviar', [
	'uses' => 'OrdeneController@updatenviar',
	'as' => 'ordene.updatenviar'
	]);


Route::get('ordene/compra', [
	'uses' => 'OrdeneController@compra',
	'as' => 'ordene.compra']);

Route::post('ordene/store_compra', [
	'uses' => 'OrdeneController@store_compra',
	'as' => 'ordene.store_compra'
	]);


Route::get('ordene/{id}/showpago', [
	'uses' => 'OrdeneController@showpago',
	'as' => 'ordene.showpago'
	]);

Route::get('ordene/{id}/enviar', [
	'uses' => 'OrdeneController@enviar',
	'as' => 'ordene.enviar'
	]);

Route::get('ordene/enviado', [
	'uses' => 'OrdeneController@enviado',
	'as' => 'ordene.enviado']);

Route::get('ordene/{id}/imprimirorden', [
	'uses' => 'OrdeneController@imprimirorden',
	'as' => 'ordene.imprimirorden'
	]);

Route::get('ordene/reporteporenviar', [
	'uses' => 'OrdeneController@reporteporenviar',
	'as' => 'ordene.reporteporenviar']);

Route::resource('ordene','OrdeneController');
Route::get('ordene/{id}/destroy', [
	'uses' => 'OrdeneController@destroy',
	'as' => 'ordene.destroy'
	]);

Route::get('ordene/{id}/destroyenviado', [
	'uses' => 'OrdeneController@destroyenviado',
	'as' => 'ordene.destroyenviado'
	]);


/*
Route::group(['prefix' => 'configuracion'], function(){
	Route::resource('configuracion','ConfiguracionController');
	Route::get('configuracion/{id}/destroy', [
	'configuracion' => 'ConfiguracionController@destroy',
	'as' => 'configuracion.destroy'
	]);
});
*/
/*
Route::get('jesus', function()
{
	return View::make('configuracion');
});
*/

resources/views/layouts/backend/blanco.blade.php
@extends('layouts.backend.template')

@section('title','')

@section('content')
<div class="container">
   <div class="row">
       <div class="col col-md-6 col-md-offset-3"   >
           <div class="panel panel-default">
             <div class="panel-heading"><h3 class="panel-title">Gracias por su Pago !!!</h3></div>
             <div class="panel-body">
               <h4>Tu mensaje ha sido enviado, pronto responderemos a tu solicitud.</h4>
             </div>
             <div class="panel-footer">
                 <a href="{{ route('ordene.create') }}" class="btn btn-primary btn-xs">Volver</a>
               </div>
           </div>
        </div>
   </div>
</div>
@endsection

resources/views/layouts/backend/nav.blade.php
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">Seguridad y Sistema JM</a>
            </div>
            <!-- /.navbar-header -->

            <!-- /.navbar-top-links -->
            <!-- /.navbar-static-side -->
        </nav>

resources/views/layouts/backend/template.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Ing. Jesus Maria Lobaton Escobar">


	<title>@yield('title', 'Reporte su pago') | SyS JM</title>

    <!-- Bootstrap Core CSS -->
    {!! Html::style('../themes/bower_components/bootstrap/dist/css/bootstrap.css') !!}

    <!-- MetisMenu CSS -->
    {!! Html::style('../themes/bower_components/metisMenu/dist/metisMenu.min.css') !!}

    <!-- Timeline CSS -->
    {!! Html::style('../themes/dist/css/timeline.css') !!}

    <!-- Custom CSS -->
    {!! Html::style('../themes/dist/css/sb-admin-2.css') !!}

    <!-- Custom Fonts -->
    {!! Html::style('../themes/bower_components/font-awesome/css/font-awesome.min.css') !!}


    {!! Html::style('../plugins/datepicker/css/datepicker.css') !!}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesnt work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js?ver=3.4.2" type="text/javascript"></script>

	{!! Html::style('css/estilo.css') !!}

<!-- link href="http://fonts.googleapis.com/css?family=Droid+Sans|Droid+Serif:400,400italic,700italic" rel="stylesheet" type="text/css" -->

</head>

<body>
    <div id="wrapper">
        <!-- Navigation -->
        @include('layouts.backend.nav')

        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">@yield('title')</h1>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
				<!-- MENSAJES DEL SISTEMA -->
			    @include('flash::message')

			    <!-- MENSAJES DE ERRORDEL SISTEMA -->
			    @include('partials.errors')

                @yield('content')
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

	@include('layouts.footer')
    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
        {!! Html::script('../themes/bower_components/jquery/dist/jquery.min.js') !!}

    <!-- Bootstrap Core JavaScript -->
        {!! Html::script('../themes/bower_components/bootstrap/dist/js/bootstrap.min.js') !!}

    <!-- Metis Menu Plugin JavaScript -->
        {!! Html::script('../themes/bower_components/metisMenu/dist/metisMenu.min.js') !!}

    <!-- Custom Theme JavaScript -->
        {!! Html::script('../themes/dist/js/sb-admin-2.js') !!}

        {!! Html::script('../plugins/datepicker/js/bootstrap-datepicker.min.js') !!}

        {!! Html::script('../plugins/moneda/jquery.price_format.min.js') !!}

<script src="/js/jquery.PrintArea.js" type="text/JavaScript" language="javascript"></script>

        <script>

    $('#datepicker').datepicker({
        format: "dd-mm-yyyy",
        maxViewMode: 1,
        clearBtn: true,
        language: "es",
        autoclose: true
    });
        </script>
</body>
</html>