app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::resource('herramienta', 'HerramientaController');

Route::get('graciaspago',function(){

	$datos = \App\Ordenes::find(1);
	//dd($datos->inventario->descr);
	//return view('correos/graciaspago', ['datos' => $datos]);
});

Route::resource('mail','MailController');
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

//Route::pattern('id', '\d+');  //Se define solo los parametros van a hacer numeros
Route::get('/', 'PrincipalController@index');

Route::get('usuarios/{id}/restaurar', [
	'uses' => 'UsersController@restaurar',
	'as' => 'usuarios.restaurar'
	]);
Route::get('usuarios/eliminada', 'UsersController@eliminada');
Route::resource('usuarios','UsersController');


Route::resource('movil','MovilController');

Route::resource('migracion', 'MigracionController');
Route::get('migracion/imagenes', [
	'uses' => 'MigracionController@imagenes',
	'as' => 'migracion.imagenes']);
Route::post('migracion/saveimagenes', [
	'uses' => 'MigracionController@saveimagenes',
	'as' => 'migracion.saveimagenes']);
/*
Route::controller('imagenes', 'ImagenesController', [
    'anyData'  => 'imagenes.data',
    'getIndex' => 'imagenes',]);
*/

Route::get('imagenes/data', [
	'uses' => 'ImagenesController@AnyData',
	'as' => 'imagenes.data']);

/*Route::get('imagenes/index', [
	'uses' => 'ImagenesController@index',
	'as' => 'imagenes.index']);
*/
Route::get('imagenes/galeria', [
	'uses' => 'ImagenesController@galeria',
	'as' => 'imagenes.galeria']);

Route::resource('imagenes', 'ImagenesController');


//Route::controller('formulario', 'FormularioController');
Route::resource('login', 'LoginController');
Route::get('/logout', 'LoginController@logout');

//Route::controller('configuracion', 'ConfiguracionController');

//Route::resource('login','LoginController');

Route::resource('configuracion','ConfiguracionController');
Route::get('configuracion/{id}/destroy', [
	'uses' => 'ConfiguracionController@destroy',
	'as' => 'configuracion.destroy'
	]);


Route::get('banco/{id}/restaurar', [
	'uses' => 'BancoController@restaurar',
	'as' => 'banco.restaurar'
	]);
Route::get('banco/eliminada', 'BancoController@eliminada');
Route::get('banco/listado', 'BancoController@listado');

Route::resource('banco','BancoController');
Route::get('banco/{id}/destroy', [
	'uses' => 'BancoController@destroy',
	'as' => 'banco.destroy'
	]);

Route::get('encomienda/eliminada', 'EncomiendaController@eliminada');
Route::resource('encomienda','EncomiendaController');
Route::get('encomienda/{encomienda}/destroy', [
	'uses' => 'EncomiendaController@destroy',
	'as' => 'encomienda.destroy'
	]);

/*
Route::get('encomienda/eliminada', [
	'uses' => 'EncomiendaController@eliminada',
	'as' => 'encomienda.eliminada'
	]);
*/
Route::get('encomienda/{id}/restaurar', [
	'uses' => 'EncomiendaController@restaurar',
	'as' => 'encomienda.restaurar'
	]);

Route::get('inventario/{id}/cambiaroferta/{page}', [
	'uses' => 'InventarioController@cambiaroferta',
	'as' => 'inventario.cambiaroferta'
	]);

Route::get('inventario/{id}/cambiarestatus/{page}', [
	'uses' => 'InventarioController@cambiarestatus',
	'as' => 'inventario.cambiarestatus'
	]);

Route::get('inventario/{id}/restaurar', [
	'uses' => 'InventarioController@restaurar',
	'as' => 'inventario.restaurar'
	]);
Route::get('inventario/eliminada', 'InventarioController@eliminada');
Route::resource('inventario','InventarioController');
Route::get('inventario/{id}/destroy', [
	'uses' => 'InventarioController@destroy',
	'as' => 'inventario.destroy'
	]);

/*
Route::post('ordene/updatenviar', function (Request $request)
	{
		return $request->all();
	});*/

Route::post('ordene/updatenviar', [
	'uses' => 'OrdeneController@updatenviar',
	'as' => 'ordene.updatenviar'
	]);


Route::get('ordene/compra', [
	'uses' => 'OrdeneController@compra',
	'as' => 'ordene.compra']);

Route::post('ordene/store_compra', [
	'uses' => 'OrdeneController@store_compra',
	'as' => 'ordene.store_compra'
	]);


Route::get('ordene/{id}/showpago', [
	'uses' => 'OrdeneController@showpago',
	'as' => 'ordene.showpago'
	]);

Route::get('ordene/{id}/enviar', [
	'uses' => 'OrdeneController@enviar',
	'as' => 'ordene.enviar'
	]);

Route::get('ordene/enviado', [
	'uses' => 'OrdeneController@enviado',
	'as' => 'ordene.enviado']);

Route::get('ordene/{id}/imprimirorden', [
	'uses' => 'OrdeneController@imprimirorden',
	'as' => 'ordene.imprimirorden'
	]);

Route::get('ordene/reporteporenviar', [
	'uses' => 'OrdeneController@reporteporenviar',
	'as' => 'ordene.reporteporenviar']);

Route::resource('ordene','OrdeneController');
Route::get('ordene/{id}/destroy', [
	'uses' => 'OrdeneController@destroy',
	'as' => 'ordene.destroy'
	]);

Route::get('ordene/{id}/destroyenviado', [
	'uses' => 'OrdeneController@destroyenviado',
	'as' => 'ordene.destroyenviado'
	]);


/*
Route::group(['prefix' => 'configuracion'], function(){
	Route::resource('configuracion','ConfiguracionController');
	Route::get('configuracion/{id}/destroy', [
	'configuracion' => 'ConfiguracionController@destroy',
	'as' => 'configuracion.destroy'
	]);
});
*/
/*
Route::get('jesus', function()
{
	return View::make('configuracion');
});
*/

app/Http/Controllers/ImagenesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Laracasts\Flash\Flash;
use Illuminate\Routing\Route;
use App\Inv_imag;
use App\Inventario;
use Yajra\Datatables\Facades\Datatables;

class ImagenesController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->beforeFilter('@find',['only' => ['edit','update','create']]);

        $this->array_inventario = Inventario::BusquedaBase()->orderBy('descr', 'asc')->lists('descr','id');

    }

    public function find(Route $route){
        //dd($route->getParameter('imagenes'));
        $this->datos = Inv_imag::find($route->getParameter('imagenes'));
        //return $this->datos;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //$imagenes = Inv_imag::OrderBy('id')->paginate(20);
       // $imagenes = Datatables::eloquent(Inv_imag::query())->make(true);
        //dd($imagenes);
        //dd($imagenes[0]->urlimagen);
        return view('imagenes.index',['buscar' => $request->buscar]);//('datos'  => $imagenes,);
    }

    /**
     * Process datatables ajax request.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function anyData()
    {
//        ->editColumn('inventario_id', '{{$id}}')

//        $imagenes = Inv_imag::OrderBy('id')->get();

$imagenes = Inv_imag::join('inventario', 'inv_imag.inventario_id', '=', 'inventario.id')
->select(['inventario.descr', 'inv_imag.id','inv_imag.urlimagen', 'inv_imag.codpro']);

//dd($imagenes);
/*
$posts = Post::join('users', 'posts.user_id', '=', 'users.id')
            ->select(['posts.id', 'posts.title', 'users.name', 'users.email', 'posts.created_at', 'posts.updated_at']);
*/        //$imagenes = Datatables::eloquent(Inv_imag::query())
        $data = Datatables::of($imagenes)
        ->addColumn('accion', '<a class="fa fa-truck" data-toggle="tooltip" data-placement="top" title="Edit" href="{{ route(\'imagenes.edit\',$id)  }}"><i class="fa fa-truck"></i></a>')


        ->make(true);
        return $data;

        //return Datatables::of(User::query())->make(true);
    }


    public function galeria(Request $request)
    {
        //dd('ddd');
        $imagenes = Inv_imag::OrderBy('id')->get();
        //dd($imagenes[0]->urlimagen);
        return view('imagenes.ver',['imagenes' => $imagenes,
                                      'buscar'   => $request->buscar]);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //$array_inventario     = Inventario::orderBy('descr', 'asc')->lists('descr','id');
        return view('imagenes.create', ['array_inventario' => $this->array_inventario]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->file('urlimagen'))
        {
       //obtenemos el nombre del archivo
        $nombre = $request->file('urlimagen')->getClientOriginalName();
       //indicamos que queremos guardar un nuevo archivo en el disco local
       \Storage::disk('imagenes_app')->put($nombre,  \File::get($request->file('urlimagen')));
       $path_imagen = 'http://www.seguridadsistema.com.ve/app/imagenes/'.$nombre;

        $datos = new Inv_imag($request->all());
        $d = Inventario::BuscarProducto($datos->inventario_id);
        $datos->codpro = $d->codpro;
        $datos->urlimagen = $path_imagen;
        $datos->save();
        Flash::success("Se ha registrado ".$datos->codpro. "de forma exitosa!");
        return redirect()->route('imagenes.index');

        }else{
            //Flash::error("Debe seleccionar un archivo de Tipo Excel o CSV");
        }
    }

    public function saveArchivo($file)
    {
       //obtenemos el campo file definido en el formulario
       //$file = $request->file('archivo');

       //obtenemos el nombre del archivo
       $nombre = $file->getClientOriginalName();

       //indicamos que queremos guardar un nuevo archivo en el disco local
       \Storage::disk('local')->put($nombre,  \File::get($file));
        //$url = $public_path.'/public/imagenes/'.$request->archivo;
       //return "archivo guardado";
       // dd("dddd");
       //dd(\Storage::disk('local'));
        return \Storage::disk('local');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('imagenes.edit', ['datos' => $this->datos,
            'array_inventario' => $this->array_inventario]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
     //dd('aaaa');
        //$conf = $this->datos->delete();
        $datos = Inv_imag::find($id);
        $datos->delete();
        Flash::error("Se ha eliminado de forma exitosa!");
        return redirect()->route('imagenes.index');
    }
}

resources/views/imagenes/create.blade.php
@extends('layouts.template')

@section('title','Agregar una Imagen')

@section('content')
	<div class="tabla_principalv2 form-horizontal">

	{!! Form::open(['route' => ['imagenes.store'], 'method' => 'POST' ,'class'=>"form-horizontal" ,'files' => true, 'enctype'=>'multipart/form-data']) !!}

<div class="panel panel-anaranja">
	<div class="panel-heading">
		<h3 class="panel-title"></h3>
	</div>
	<div class="panel-body">

		<div class="form-group">
			{!! Form::label('inventario_id','Inventario'); !!}
			{!! Form::select('inventario_id', $array_inventario, null, ['class' => 'form-control', 'placeholder' => '', 'required']) !!}
		</div>
		<!-- div class="form-group">
			{!! Form::label('codpro','Código'); !!}
			{!! Form::text('codpro',NULL, ['class' => 'form-control', 'placeholder' => 'Indique el Código del Producto', 'required']); !!}
		</div -->
		<!-- div class="form-group">
			{!! Form::label('urlimagen','Descripción'); !!}
			{!! Form::text('urlimagen',NULL, ['class' => 'form-control', 'placeholder' => 'Indique la URL de la Imagen Ej: http://www.seguridadsistema.com.ve/app/imagenes/', 'required']); !!}
		</div -->

	    <div class='form-group'>
	    	{!! Form::label('urlimagen','Selecione una imagen'); !!}
	        {!! Form::file('urlimagen',null); !!}
	    </div>

		<div class="form-group">
			<a class="btn btn-primary" href="{{ route('imagenes.index') }}" role="button"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Atras</a>

			{!! Form::submit('Guardar', ['class' => 'btn btn-success']) !!}
		</div>

</div>

	{!! Form::close() !!}


</div>

@endsection

resources/views/imagenes/edit.blade.php
@extends('layouts.template')

@section('title','Editar una Imagen')

@section('content')

	{!! Form::open(['route' => ['imagenes.update', $datos->id], 'method' => 'POST' ,'class'=>"form-horizontal" ,'files' => true, 'enctype'=>'multipart/form-data']) !!}

		<div class="form-group">
			{!! Form::label('inventario_id','Inventario'); !!}
			{!! Form::select('inventario_id', $array_inventario, $datos->inventario_id, ['class' => 'form-control', 'placeholder' => '', 'required']) !!}
		</div>
		<div class="form-group">
			{!! Form::label('codpro','Código'); !!}
			{!! Form::text('codpro',$datos->codpro, ['class' => 'form-control', 'placeholder' => 'Indique el Código del Producto', 'required']); !!}
		</div>
		<div class="form-group">
			{!! Form::label('urlimagen2','URL Imagen'); !!}
			{!! Form::text('urlimagen2',$datos->urlimagen, ['class' => 'form-control', 'placeholder' => 'Indique la URL de la Imagen Ej: http://www.seguridadsistema.com.ve/app/imagenes/', 'required']); !!}
		</div>

	    <div class='form-group'>
	    	{!! Form::label('urlimagen','Selecione una imagen'); !!}
	        {!! Form::file('urlimagen',null); !!}
	    </div>

		<div class="form-group">
			<a class="btn btn-primary" href="{{ route('imagenes.index') }}" role="button"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Atras</a>

			{!! Form::submit('Guardar', ['class' => 'btn btn-success']) !!}
		</div>

	{!! Form::close() !!}

@endsection

resources/views/imagenes/index.blade.php
@extends('layouts.template')

@section('title','Listado de las Imagenes')

@section('content')
<style type="text/css" media="screen">
.toolbar2 {
    float: left;
}
</style>
<div class="table-responsive">

<div >
<a href="{{ route('imagenes.create') }}" class="btn btn-success boton" role="button"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Agregar</a>

<a href="{{ route('imagenes.galeria') }}" class="btn btn-primary boton" role="button"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> ir a Galeria</a>

{!! Form::open(['route' => 'imagenes.index', 'method' => 'GET', 'class' => 'navbar-form pull-right']) !!}
    <div class="pull-right input-group">
        {!! Form::text('buscar', $buscar, ['class'=> 'form-control', 'placeholder' => 'Buscar ...', 'aria-describedby' => 'search']) !!}
      <span class="input-group-btn">
        <button class="btn btn-secondary" type="button"  id='search'><i class="fa fa-search"></i></button>
      </span>
    </div>
{!! Form::close()!!}
</div>
<hr>
</div>

<table class="table table-striped table-bordered" id="users-table" width="100%">
    <thead>
        <tr>
            <td>{{ "Productos" }}</td>
            <td>{{ "Código" }}</td>
            <td>{{ "URL" }}</td>
            <td>{{ "Acción" }}</td>
        </tr>
    </thead>
</table>
<script type="text/javascript">
$(document).ready(function() {
    $('#users-table').DataTable({
            processing: true,
            serverSide: true,
            order: [[ 1, "asc" ]],
            pagingType: "simple_numbers",
            ajax: '{!! route('imagenes.data') !!}',
            language: {
                "url": "//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json"
            },
            columns: [
                { data: 'descr', name: 'inventario.descr' },
                { data: 'codpro', name: 'inv_imag.codpro' },
                { data: 'urlimagen', name: 'inv_imag.urlimagen' },
                { data: 'accion', name: 'accion' }

            ]
        });
});
</script>
@endsection

resources/views/imagenes/index2.blade.php
@extends('layouts.template')

@section('title','Listado de las Imagenes')

@section('content')
<div class="table-responsive">

<div >
<a href="{{ route('imagenes.create') }}" class="btn btn-success boton" role="button"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Agregar</a>

<a href="{{ route('imagenes.galeria') }}" class="btn btn-primary boton" role="button"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> ir a Galeria</a>

{!! Form::open(['route' => 'imagenes.index', 'method' => 'GET', 'class' => 'navbar-form pull-right']) !!}
    <div class="pull-right input-group">
        {!! Form::text('buscar', $buscar, ['class'=> 'form-control', 'placeholder' => 'Buscar ...', 'aria-describedby' => 'search']) !!}
      <span class="input-group-btn">
        <button class="btn btn-secondary" type="button"  id='search'><i class="fa fa-search"></i></button>
      </span>
    </div>
{!! Form::close()!!}
</div>
<hr>
<div class="centrado">
<table class="table table-hover table-bordered table-striped">
    <thead>
        <tr>
            <td>{{ "Productos" }}</td>
            <td>{{ "Código" }}</td>
            <td>{{ "URL" }}</td>
            <td>{{ "Acción" }}</td>
        </tr>
    </thead>
    <tbody>
        @if(!empty($datos))
        @foreach ($datos as $dato)
            <tr>
                <td>{{ $dato->inventario->descr }}</td>
                <td>{{ $dato->codpro }}</td>
                <td>{{ $dato->urlimagen }}</td>

                <td class="acciones">
                <div class="dropdown">
                  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"> <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                    <li><a href="{{ route('imagenes.edit',$dato->id) }}"><span class="fa fa-truck" aria-hidden="true"></span> Ver Imagen</a> </li>

                    <li role="separator" class="divider"></li>
                    <li><a href="{{ route('imagenes.edit', $dato->id) }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Editar </a></li>
                    <li><a href="{{ route('imagenes.destroy', $dato->id) }}" onclick="return confirm('Esta seguro que desea Eliminarlo?')"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Eliminar </a></li>
                  </ul>
                </div>
                </td>
            </tr>
        @endforeach
        @else
            <tr>
                <td colspan="6">
                    <center>{{ "NO EXISTEN DATOS" }}</center>
                </td>
            </tr>
        @endif

    </tbody>
</table>
    <div class="text-center">
        {!! $datos->render() !!}
    </div>
</div>
</div>

<table class="table table-bordered" id="users-table">
    <thead>
        <tr>
            <th>inventario_id</th>
            <th>codpro</th>
            <th>urlimagen</th>
        </tr>
    </thead>
</table>
<script type="text/javascript">
$(document).ready(function() {
/*
        $('#users-table').DataTable({a
            processing: true,
            serverSide: true,
            ajax: 'http://datatables.yajrabox.com/eloquent/basic-data'
        });*/

$('#users-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('imagenes.data') !!}',
        columns: [
            { data: 'inventario_id', name: 'inventario_id' },
            { data: 'codpro', name: 'codpro' },
            { data: 'urlimagen', name: 'urlimagen' }
        ]
    });

});



</script>
@endsection

resources/views/imagenes/ver.blade.php
@extends('layouts.template')

@section('title','Galeria de Imagenes')

@section('content')
<div class="table-responsive">

<a class="btn btn-primary" href="{{ route('imagenes.index') }}" role="button"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Atras</a>

{!! Form::open(['route' => 'imagenes.index', 'method' => 'GET', 'class' => 'navbar-form pull-right']) !!}
        <div class="input-group custom-search-form">
            {!! Form::text('buscar', $buscar, ['class'=> 'form-control', 'placeholder' => 'Buscar ...', 'aria-describedby' => 'search']) !!}
            <span class="input-group-btn"><button type="submit" class="btn btn-default" id='search'><i class="fa fa-search"></i></button></span>
        </div>
    {!! Form::close()!!}
<hr>

<div class="row">
    @foreach ($imagenes as $imag)
<div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
          <a href="#" class="thumbnailj">
            <img src="{{ $imag->urlimagen }}" WIDTH="250px" height="200px">
        </a>
      </div>
    </div>
</div>
    @endforeach
</div>

</div>

@endsection