app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::resource('herramienta', 'HerramientaController');

Route::get('graciaspago',function(){

	$datos = \App\Ordenes::find(1);
	//dd($datos->inventario->descr);
	//return view('correos/graciaspago', ['datos' => $datos]);
});

Route::resource('mail','MailController');
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

//Route::pattern('id', '\d+');  //Se define solo los parametros van a hacer numeros
Route::get('/', 'PrincipalController@index');

Route::get('usuarios/{id}/restaurar', [
	'uses' => 'UsersController@restaurar',
	'as' => 'usuarios.restaurar'
	]);
Route::get('usuarios/eliminada', 'UsersController@eliminada');
Route::resource('usuarios','UsersController');


Route::resource('movil','MovilController');

Route::resource('migracion', 'MigracionController');
Route::get('migracion/imagenes', [
	'uses' => 'MigracionController@imagenes',
	'as' => 'migracion.imagenes']);
Route::post('migracion/saveimagenes', [
	'uses' => 'MigracionController@saveimagenes',
	'as' => 'migracion.saveimagenes']);
/*
Route::controller('imagenes', 'ImagenesController', [
    'anyData'  => 'imagenes.data',
    'getIndex' => 'imagenes',]);
*/

Route::get('imagenes/data', [
	'uses' => 'ImagenesController@AnyData',
	'as' => 'imagenes.data']);

/*Route::get('imagenes/index', [
	'uses' => 'ImagenesController@index',
	'as' => 'imagenes.index']);
*/
Route::get('imagenes/galeria', [
	'uses' => 'ImagenesController@galeria',
	'as' => 'imagenes.galeria']);

Route::resource('imagenes', 'ImagenesController');


//Route::controller('formulario', 'FormularioController');
Route::resource('login', 'LoginController');
Route::get('/logout', 'LoginController@logout');

//Route::controller('configuracion', 'ConfiguracionController');

//Route::resource('login','LoginController');

Route::resource('configuracion','ConfiguracionController');
Route::get('configuracion/{id}/destroy', [
	'uses' => 'ConfiguracionController@destroy',
	'as' => 'configuracion.destroy'
	]);


Route::get('banco/{id}/restaurar', [
	'uses' => 'BancoController@restaurar',
	'as' => 'banco.restaurar'
	]);
Route::get('banco/eliminada', 'BancoController@eliminada');
Route::get('banco/listado', 'BancoController@listado');

Route::resource('banco','BancoController');
Route::get('banco/{id}/destroy', [
	'uses' => 'BancoController@destroy',
	'as' => 'banco.destroy'
	]);

Route::get('encomienda/eliminada', 'EncomiendaController@eliminada');
Route::resource('encomienda','EncomiendaController');
Route::get('encomienda/{encomienda}/destroy', [
	'uses' => 'EncomiendaController@destroy',
	'as' => 'encomienda.destroy'
	]);

/*
Route::get('encomienda/eliminada', [
	'uses' => 'EncomiendaController@eliminada',
	'as' => 'encomienda.eliminada'
	]);
*/
Route::get('encomienda/{id}/restaurar', [
	'uses' => 'EncomiendaController@restaurar',
	'as' => 'encomienda.restaurar'
	]);

Route::get('inventario/{id}/cambiaroferta/{page}', [
	'uses' => 'InventarioController@cambiaroferta',
	'as' => 'inventario.cambiaroferta'
	]);

Route::get('inventario/{id}/cambiarestatus/{page}', [
	'uses' => 'InventarioController@cambiarestatus',
	'as' => 'inventario.cambiarestatus'
	]);

Route::get('inventario/{id}/restaurar', [
	'uses' => 'InventarioController@restaurar',
	'as' => 'inventario.restaurar'
	]);
Route::get('inventario/eliminada', 'InventarioController@eliminada');
Route::resource('inventario','InventarioController');
Route::get('inventario/{id}/destroy', [
	'uses' => 'InventarioController@destroy',
	'as' => 'inventario.destroy'
	]);

/*
Route::post('ordene/updatenviar', function (Request $request)
	{
		return $request->all();
	});*/

Route::post('ordene/updatenviar', [
	'uses' => 'OrdeneController@updatenviar',
	'as' => 'ordene.updatenviar'
	]);


Route::get('ordene/compra', [
	'uses' => 'OrdeneController@compra',
	'as' => 'ordene.compra']);

Route::post('ordene/store_compra', [
	'uses' => 'OrdeneController@store_compra',
	'as' => 'ordene.store_compra'
	]);


Route::get('ordene/{id}/showpago', [
	'uses' => 'OrdeneController@showpago',
	'as' => 'ordene.showpago'
	]);

Route::get('ordene/{id}/enviar', [
	'uses' => 'OrdeneController@enviar',
	'as' => 'ordene.enviar'
	]);

Route::get('ordene/enviado', [
	'uses' => 'OrdeneController@enviado',
	'as' => 'ordene.enviado']);

Route::get('ordene/{id}/imprimirorden', [
	'uses' => 'OrdeneController@imprimirorden',
	'as' => 'ordene.imprimirorden'
	]);

Route::get('ordene/reporteporenviar', [
	'uses' => 'OrdeneController@reporteporenviar',
	'as' => 'ordene.reporteporenviar']);

Route::resource('ordene','OrdeneController');
Route::get('ordene/{id}/destroy', [
	'uses' => 'OrdeneController@destroy',
	'as' => 'ordene.destroy'
	]);

Route::get('ordene/{id}/destroyenviado', [
	'uses' => 'OrdeneController@destroyenviado',
	'as' => 'ordene.destroyenviado'
	]);


/*
Route::group(['prefix' => 'configuracion'], function(){
	Route::resource('configuracion','ConfiguracionController');
	Route::get('configuracion/{id}/destroy', [
	'configuracion' => 'ConfiguracionController@destroy',
	'as' => 'configuracion.destroy'
	]);
});
*/
/*
Route::get('jesus', function()
{
	return View::make('configuracion');
});
*/

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>@yield('title', 'Bienvenido') | SyS JM</title>

@section('cabecera')
	{!! Html::style('css/bootstrap.css') !!}
	{!! Html::style('css/estilo.css') !!}

		<!-- Scripts -->
	{!! Html::script('http://code.jquery.com/jquery-1.11.3.js') !!}

	{!! Html::script('js/bootstrap.min.js') !!}

@show
	<!-- Fonts -->
	<!-- link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css' -->
	<link href='http://fonts.googleapis.com/css?family=Ubuntu&subset=latin,greek' rel='stylesheet' type='text/css'>

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	<!-- BARRA DE MENU -->
	<div class="table-responsive">

	@include('layouts.nav')

	<div class="tabla_principal">
		<div class="centrado titulo ">
	    	@yield('title')
		</div>

		<!-- MENSAJES DEL SISTEMA -->
	    @include('flash::message')

	    <!-- MENSAJES DE ERRORDEL SISTEMA -->
	    @include('partials.errors')

	    <!-- CONTENIDO -->
		@yield('content')
	</div>

	</div>


@include('layouts.footer')
</body>
</html>

resources/views/layouts/menu.blade.php
<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" value="llllllllllllll">
 </button>
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li>
                <a href="/"><i class="glyphicon glyphicon-home"></i> Principal</a>
            </li>
            <li>
            <a href="#"><i class="glyphicon glyphicon-th-large"></i> Archivo<span class="fa arrow"></span></a>
            <ul class="nav nav-second-level">
                <li>
                    <a href="#"><i class="glyphicon glyphicon-user"></i> Usuario<span class="fa arrow"></span></a>
                     <ul class="nav nav-third-level">
                        <li>
                            <a href="{{ route('usuarios.index') }}"><i class="glyphicon glyphicon-user"></i> Listados</a>
                        </li>
                        <li>
                            <a href="{{ url('usuarios/eliminada') }}"><i class="glyphicon glyphicon-repeat"></i> Eliminadas</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#"><i class="glyphicon glyphicon-barcode"></i> Encomienda<span class="fa arrow"></span></a>
                     <ul class="nav nav-third-level">
                        <li>
                            <a href="{{ route('encomienda.index') }}"><i class="glyphicon glyphicon-barcode"></i> Listados</a>
                        </li>
                        <li>
                            <a href="{{ url('encomienda/eliminada') }}"><i class="glyphicon glyphicon-repeat"></i> Eliminadas</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#"><i class="glyphicon glyphicon-signal"></i> Banco<span class="fa arrow"></span></a>
                     <ul class="nav nav-third-level">
                        <li>
                            <a href="{{ route('banco.index') }}"><i class="glyphicon glyphicon-signal"></i> Listados</a>
                        </li>
                        <li>
                            <a href="{{ url('banco/eliminada') }}"><i class="glyphicon glyphicon-repeat"></i> Eliminadas</a>
                        </li>
                        <li>
                            <a href="{{ url('banco/listado') }}"><i class="glyphicon glyphicon-signal"></i> Mostrar</a>
                        </li>

                    </ul>
                </li>

                <li>
                    <a href="#"><i class="glyphicon glyphicon-tag"></i> Tipo de Pago<span class="fa arrow"></span></a>
                     <ul class="nav nav-third-level">
                        <li>
                            <a href="{{ route('inventario.index') }}"><i class="glyphicon glyphicon-tag"></i> Listados</a>
                        </li>
                        <li>
                            <a href="{{ route('inventario.index') }}"><i class="glyphicon glyphicon-repeat"></i> Eliminadas</a>
                        </li>
                    </ul>
                </li>

                <li>
                    <a href="#"><i class="glyphicon glyphicon-cog"></i> Configuración<span class="fa arrow"></span></a>
                     <ul class="nav nav-third-level">
                        <li>
                            <a href="{{ route('configuracion.index') }}"><i class="glyphicon glyphicon-cog"></i> Listados</a>
                        </li>
                        <li>
                            <a href="{{ route('configuracion.index') }}"><i class="glyphicon glyphicon-cog"></i> Eliminadas</a>
                        </li>
                    </ul>
                </li>
            </ul>
                <!-- /.nav-second-level -->
            </li>
            <li>
                <a href="#"><i class="glyphicon glyphicon-th-list"></i> Ordenes<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{{ route('ordene.index') }}"><i class="glyphicon glyphicon-list-alt"></i> Ordenes</a>
                    </li>
                    <li>
                        <a href="{{ route('ordene.enviado') }}"><i class="fa fa-truck"></i> Enviados</a>
                   </li>
                    <li>
                        <a href="{{ url('inventario/eliminada') }}"><i class="glyphicon glyphicon-repeat"></i> Eliminadas</a>
                    </li>
                    <li>
                        <a href="{{ route('ordene.compra') }}"><i class="glyphicon glyphicon-list-alt"></i> Enviar solicitud de Pago</a>
                    </li>

                </ul>
            </li>

            <li>
                <a href="#"><i class="glyphicon glyphicon-th-list"></i> Producto<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{{ route('inventario.index') }}"><i class="glyphicon glyphicon-list-alt"></i> Productos</a>
                    </li>
                    <li>
                        <a href="{{ route('imagenes.index') }}"><i class="glyphicon glyphicon-picture"></i> Imagenes</a>
                    </li>
                    <li>
                        <a href="{{ url('inventario/eliminada') }}"><i class="glyphicon glyphicon-repeat"></i> Eliminadas</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#"><i class="fa fa-sitemap fa-fw"></i> Migraciones<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{{ route('migracion.index') }}"><i class="glyphicon glyphicon-list-alt"></i> Productos</a>
                    </li>
                    <li>
                        <a href="{{ route('migracion.imagenes') }}"><i class="glyphicon glyphicon-picture"></i> Imágenes</a>
                    </li>

                </ul>
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>

resources/views/layouts/nav.blade.php
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">Seguridad y Sistema JM</a>
            </div>
            <!-- /.navbar-header -->
            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-messages">
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>Read All Messages</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-messages -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-tasks fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-tasks">
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 1</strong>
                                        <span class="pull-right text-muted">40% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                            <span class="sr-only">40% Complete (success)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 2</strong>
                                        <span class="pull-right text-muted">20% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                                            <span class="sr-only">20% Complete</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 3</strong>
                                        <span class="pull-right text-muted">60% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                            <span class="sr-only">60% Complete (warning)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 4</strong>
                                        <span class="pull-right text-muted">80% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                                            <span class="sr-only">80% Complete (danger)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>See All Tasks</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-tasks -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                        <li>
                            <a href="{{ route('ordene.index') }}">
                                <div>
                                    <i class="fa fa-comment fa-fw"></i> Nuevos Pedidos
                                    <span class="pull-right text-muted small">{{ (is_object($datos_pedido)) ? $datos_pedido[0]->fecha->diffForHumans() : '' }}</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="{{ route('ordene.index') }}">
                                <div>

                                    <i class="glyphicon glyphicon-hourglass fa-fw"></i> Por Enviar
                                    <span class="pull-right text-muted small">{{ (isset($PorEnviar))?  $PorEnviar ." Articulos": '' }}</span>
                                   </span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="{{ route('ordene.enviado') }}">
                                <div>
                                    <i class="fa fa-truck fa-fw"></i> Enviado
                                    <span class="pull-right text-muted small">{{ (isset($Enviado))? (is_object($Enviado)) ? $Enviado[0]->fecha->diffForHumans() : '' : ''     }}</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-tasks fa-fw"></i> New Task
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>See All Alerts</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-alerts -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">{{ Auth::user()->name }}
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="{{ route('usuarios.edit', Auth::user()->id) }}"><i class="fa fa-user fa-fw"></i> Editar</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="{{ ('logout') }}"><i class="fa fa-sign-out fa-fw"></i> Cerrar Sesión</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->
                @include('layouts.menu')
            <!-- /.navbar-static-side -->
        </nav>

resources/views/layouts/principal.blade.php
@extends('layouts.template')

@section('title','Bienvenido ...')

@section('content')
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="glyphicon glyphicon-list-alt fa-4x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">{!! $count_inv !!}</div>
                                    <div>Productos</div>
                                </div>
                            </div>
                        </div>
                        <a href="{{ route('inventario.index') }}">
                            <div class="panel-footer">
                                <span class="pull-left">Ver Detalles</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-yellow">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-shopping-cart fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">{!! $count_ord !!}</div>
                                    <div>Orden de Pago</div>
                                </div>
                            </div>
                        </div>
                        <a href="{{ route('ordene.index') }}">
                            <div class="panel-footer">
                                <span class="pull-left">Ver Detalles</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-truck fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">{!! $count_ord_env !!}</div>
                                    <div>Ordenes Enviados</div>
                                </div>
                            </div>
                        </div>
                        <a href="{{ route('ordene.enviado') }}">
                            <div class="panel-footer">
                                <span class="pull-left">Ver Detalles</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-comments fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">0</div>
                                    <div>Prueba</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">Ver Detalles</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            <!-- /.row -->
<div class="col-lg-8">
</div>
<div class="col-lg-4">

    <!-- a class="twitter-timeline"  href="https://twitter.com/SyS_JM" data-widget-id="672994037905887232">Tweets por el @SyS_JM.</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script -->

</div>
<hr>
<div class="col-lg">

<div class="panel-body">
<div class="text-center">
    <a class="btn btn-social-icon btn-dropbox" href=""><i class="fa fa-dropbox"></i></a>
    <a class="btn btn-social-icon btn-facebook" href=""><i class="fa fa-facebook"></i></a>
    <a class="btn btn-social-icon btn-github" href=""><i class="fa fa-github"></i></a>
    <a class="btn btn-social-icon btn-google-plus" href=""><i class="fa fa-google-plus"></i></a>
    <a class="btn btn-social-icon btn-instagram" href=""><i class="fa fa-instagram"></i></a>
    <a class="btn btn-social-icon btn-twitter" href=""><i class="fa fa-twitter"></i></a>
</div>
</div>
</div>
@endsection