app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::resource('herramienta', 'HerramientaController');

Route::get('graciaspago',function(){

	$datos = \App\Ordenes::find(1);
	//dd($datos->inventario->descr);
	//return view('correos/graciaspago', ['datos' => $datos]);
});

Route::resource('mail','MailController');
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

//Route::pattern('id', '\d+');  //Se define solo los parametros van a hacer numeros
Route::get('/', 'PrincipalController@index');

Route::get('usuarios/{id}/restaurar', [
	'uses' => 'UsersController@restaurar',
	'as' => 'usuarios.restaurar'
	]);
Route::get('usuarios/eliminada', 'UsersController@eliminada');
Route::resource('usuarios','UsersController');


Route::resource('movil','MovilController');

Route::resource('migracion', 'MigracionController');
Route::get('migracion/imagenes', [
	'uses' => 'MigracionController@imagenes',
	'as' => 'migracion.imagenes']);
Route::post('migracion/saveimagenes', [
	'uses' => 'MigracionController@saveimagenes',
	'as' => 'migracion.saveimagenes']);
/*
Route::controller('imagenes', 'ImagenesController', [
    'anyData'  => 'imagenes.data',
    'getIndex' => 'imagenes',]);
*/

Route::get('imagenes/data', [
	'uses' => 'ImagenesController@AnyData',
	'as' => 'imagenes.data']);

/*Route::get('imagenes/index', [
	'uses' => 'ImagenesController@index',
	'as' => 'imagenes.index']);
*/
Route::get('imagenes/galeria', [
	'uses' => 'ImagenesController@galeria',
	'as' => 'imagenes.galeria']);

Route::resource('imagenes', 'ImagenesController');


//Route::controller('formulario', 'FormularioController');
Route::resource('login', 'LoginController');
Route::get('/logout', 'LoginController@logout');

//Route::controller('configuracion', 'ConfiguracionController');

//Route::resource('login','LoginController');

Route::resource('configuracion','ConfiguracionController');
Route::get('configuracion/{id}/destroy', [
	'uses' => 'ConfiguracionController@destroy',
	'as' => 'configuracion.destroy'
	]);


Route::get('banco/{id}/restaurar', [
	'uses' => 'BancoController@restaurar',
	'as' => 'banco.restaurar'
	]);
Route::get('banco/eliminada', 'BancoController@eliminada');
Route::get('banco/listado', 'BancoController@listado');

Route::resource('banco','BancoController');
Route::get('banco/{id}/destroy', [
	'uses' => 'BancoController@destroy',
	'as' => 'banco.destroy'
	]);

Route::get('encomienda/eliminada', 'EncomiendaController@eliminada');
Route::resource('encomienda','EncomiendaController');
Route::get('encomienda/{encomienda}/destroy', [
	'uses' => 'EncomiendaController@destroy',
	'as' => 'encomienda.destroy'
	]);

/*
Route::get('encomienda/eliminada', [
	'uses' => 'EncomiendaController@eliminada',
	'as' => 'encomienda.eliminada'
	]);
*/
Route::get('encomienda/{id}/restaurar', [
	'uses' => 'EncomiendaController@restaurar',
	'as' => 'encomienda.restaurar'
	]);

Route::get('inventario/{id}/cambiaroferta/{page}', [
	'uses' => 'InventarioController@cambiaroferta',
	'as' => 'inventario.cambiaroferta'
	]);

Route::get('inventario/{id}/cambiarestatus/{page}', [
	'uses' => 'InventarioController@cambiarestatus',
	'as' => 'inventario.cambiarestatus'
	]);

Route::get('inventario/{id}/restaurar', [
	'uses' => 'InventarioController@restaurar',
	'as' => 'inventario.restaurar'
	]);
Route::get('inventario/eliminada', 'InventarioController@eliminada');
Route::resource('inventario','InventarioController');
Route::get('inventario/{id}/destroy', [
	'uses' => 'InventarioController@destroy',
	'as' => 'inventario.destroy'
	]);

/*
Route::post('ordene/updatenviar', function (Request $request)
	{
		return $request->all();
	});*/

Route::post('ordene/updatenviar', [
	'uses' => 'OrdeneController@updatenviar',
	'as' => 'ordene.updatenviar'
	]);


Route::get('ordene/compra', [
	'uses' => 'OrdeneController@compra',
	'as' => 'ordene.compra']);

Route::post('ordene/store_compra', [
	'uses' => 'OrdeneController@store_compra',
	'as' => 'ordene.store_compra'
	]);


Route::get('ordene/{id}/showpago', [
	'uses' => 'OrdeneController@showpago',
	'as' => 'ordene.showpago'
	]);

Route::get('ordene/{id}/enviar', [
	'uses' => 'OrdeneController@enviar',
	'as' => 'ordene.enviar'
	]);

Route::get('ordene/enviado', [
	'uses' => 'OrdeneController@enviado',
	'as' => 'ordene.enviado']);

Route::get('ordene/{id}/imprimirorden', [
	'uses' => 'OrdeneController@imprimirorden',
	'as' => 'ordene.imprimirorden'
	]);

Route::get('ordene/reporteporenviar', [
	'uses' => 'OrdeneController@reporteporenviar',
	'as' => 'ordene.reporteporenviar']);

Route::resource('ordene','OrdeneController');
Route::get('ordene/{id}/destroy', [
	'uses' => 'OrdeneController@destroy',
	'as' => 'ordene.destroy'
	]);

Route::get('ordene/{id}/destroyenviado', [
	'uses' => 'OrdeneController@destroyenviado',
	'as' => 'ordene.destroyenviado'
	]);


/*
Route::group(['prefix' => 'configuracion'], function(){
	Route::resource('configuracion','ConfiguracionController');
	Route::get('configuracion/{id}/destroy', [
	'configuracion' => 'ConfiguracionController@destroy',
	'as' => 'configuracion.destroy'
	]);
});
*/
/*
Route::get('jesus', function()
{
	return View::make('configuracion');
});
*/

resources/views/usuarios/create.blade.php
@extends('layouts.template')

@section('title','Agregar un Usuario')

@section('content')
	<div class="tabla_principalv2">
	{!! Form::open(['route' => 'usuarios.store', 'method' => 'POST']) !!}

		<div class="form-group">
			{!! Form::label('name','Nombre de Usuario'); !!}
			{!! Form::text('name',null, ['class' => 'form-control', 'placeholder' => 'Indique el Nombre de Usuario', 'required']); !!}
		</div>

		<div class="form-group">
			{!! Form::label('email','Correo'); !!}
			{!! Form::email('email',null, ['class' => 'form-control', 'placeholder' => 'example@gmail.com', 'required']); !!}
		</div>

		<div class="form-group">
			{!! Form::label('password','Contraseña'); !!}
			{!! Form::password('password', ['class' => 'form-control', 'placeholder' => '*************', 'required']); !!}
		</div>

		<div class="form-group">
			{!! Form::label('tipo','Tipo de Cuenta'); !!}
			{!! Form::select('tipo',[''=>'Seleccione un Nivel','usuario'=> 'Usuario','admin'=> 'Administrador'],null, ['class' => 'form-control',  'required']); !!}
		</div>


		<div class="form-group botonera" >
			<a class="btn btn-primary" href="#" role="button"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Atras</a>

			{!! Form::submit('Guardar', ['class' => 'btn btn-success glyphicon glyphicon-save']) !!}
		</div>

	{!! Form::close() !!}
	</div>
@endsection

resources/views/usuarios/edit.blade.php
@extends('layouts.template')

@section('title','Editar el usuario '.$datos->name)

@section('content')
	<div class="tabla_principalv2">
	{!! Form::open(['route' => ['usuarios.update', $datos->id], 'method' => 'PUT']) !!}

		<div class="form-group">
			{!! Form::label('name','Nombre de Usuario'); !!}
			{!! Form::text('name',$datos->name, ['class' => 'form-control', 'placeholder' => 'Indique el Nombre de Usuario', 'required']); !!}
		</div>

		<div class="form-group">
			{!! Form::label('email','Correo'); !!}
			{!! Form::email('email',$datos->email, ['class' => 'form-control', 'placeholder' => 'example@gmail.com', 'required']); !!}
		</div>

		<div class="form-group">
			{!! Form::label('password','Contraseña'); !!}
			{!! Form::password('password', ['class' => 'form-control', 'placeholder' => '*************', '']); !!}
		</div>

		<div class="form-group">
			{!! Form::label('tipo','Tipo de Cuenta'); !!}
			{!! Form::select('tipo',[''=>'Seleccione un Nivel','usuario'=> 'Usuario','admin'=> 'Administrador'], $datos->tipo,  ['class' => 'form-control', 'required']); !!}
		</div>

		<div class="form-group">
			<a class="btn btn-primary" href="{{ redirect()->back() }}" role="button"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Atras</a>

			{!! Form::submit('Guardar', ['class' => 'btn btn-success']) !!}
		</div>

	{!! Form::close() !!}
	</div>
@endsection

resources/views/usuarios/index.blade.php
@extends('layouts.template')

@section('title','Listado de Usuarios')

@section('content')
<div class="table-responsive">

<a href="{{ route('usuarios.create') }}" class="btn btn-success boton" role="button"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Agregar</a>

    {!! Form::open(['route' => 'usuarios.index', 'method' => 'GET', 'class' => 'navbar-form pull-right']) !!}
        <div class="input-group custom-search-form">
            {!! Form::text('buscar', $buscar, ['class'=> 'form-control', 'placeholder' => 'Buscar ...', 'aria-describedby' => 'search']) !!}
            <span class="input-group-btn"><button type="submit" class="btn btn-default" id='search'><i class="fa fa-search"></i></button></span>
        </div>

    {!! Form::close()!!}
<hr>

<div class="centrado">

<table class="table table-hover table-bordered table-striped">
    <thead>
        <tr>
            <td>{{ "Usuario" }}</td>
            <td>{{ "Correo" }}</td>
            <td>{{ "Tipo" }}</td>
            <td>{{ "Acciones" }}</td>
        </tr>
    </thead>
    <tbody>
        @if(!empty($datos[0]))
        @foreach ($datos as $dato)
            <tr>
                <td>{{ $dato->name }}</td>
                <td>{{ $dato->email }}</td>
                <td>{{ $dato->tipo }}</td>
                <td class="acciones">
                    <div class="btn-group" role="group" aria-label="...">
                        <a href="{{ route('usuarios.edit', $dato->id) }}" class="btn btn-primary"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                        <a href="{{ route('usuarios.destroy', $dato->id) }}" class="btn btn-danger" onclick="return confirm('Esta seguro que desea Eliminarlo?')"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                    </div>
                </td>
            </tr>
        @endforeach
        @else
            <tr>
                <td colspan="4">
                    <center>{{ "NO EXISTEN DATOS" }}</center>
                </td>
            </tr>
        @endif

    </tbody>
</table>
    <div class="text-center">
        {!! $datos->render() !!}
    </div>
</div>
</div>
@endsection